---
title: "Excel Resources"
author: "Ryan Estrellado"
date: "`r format(Sys.Date())`"
output: github_document
---

## Basic Formulas

- [Microsoft website. Includes downloadable workbook](https://support.office.com/en-us/article/overview-of-formulas-in-excel-ecfdc708-9162-49e8-b993-c311f47ca173) 
- There are a lot of YouTube videos on this topic. [Here is one example](https://youtu.be/1naiWCWfSt4)

## How Sorting Works in Excel 

Sorting rows in Excel is a really useful task, but doing it incorrectly can lead to some columns sorting and others not. When you sort, you definitely want all the cells in a row to stick together. 

- [Microsoft's tutorial on sorting cells in a data range](https://support.office.com/en-us/article/sort-data-in-a-range-or-table-62d0b95d-2a90-4610-a6ae-2e545c4a4654)

## How Dates Work in Excel 

In my talk on predicting DINC items, I subtracted one date from another to find the number of days between two dates. There are different ways to get that result in Excel. Here's more to read on this topic:

- [How to use the date format](https://support.office.com/en-us/article/Format-a-date-the-way-you-want-8E10019E-D5D8-47A1-BA95-DB95123D273E)
- [Multiple ways to find the days between two dates](https://www.online-tech-tips.com/ms-office-tips/subtract-dates-in-excel/) 
- [Microsoft's tutorial on using the `DATEDIF` formula](https://support.office.com/en-us/article/calculate-the-difference-between-two-dates-8235e7c9-b430-44ca-9425-46100a162f38)

## The Differences Between Excel and Coding 